name: Python exercise

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Run Lint
      run: |
        pipenv run lint
    - name: Run Test
      run: |
        pipenv run test
